version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.16.1
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      discovery.type: single-node
    networks:
      - elk
    ports:
      - "9200:9200"

  logstash:
    image: logstash:7.16.1
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: kibana:7.16.1
    depends_on:
      - elasticsearch
    networks:
      - elk
    ports:
      - "5601:5601"

networks:
  elk:
    driver: bridge